In [1]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from torch.nn import Softmax

In [2]:
datas = pd.read_csv('基本操作/datas/text_classify/train_tokens3.csv', sep='\t', header=None, )

In [3]:
datas.head(10)

                                    0              1
0          还有 双鸭山 到 淮阴 的 汽车票 吗 13 号 的   Travel-Query
1                          从 这里 怎么 回家   Travel-Query
2           随便 播放 一首 专辑 阁楼 里 的 佛里 的 歌     Music-Play
3                       给 看 一下 墓王之王 嘛  FilmTele-Play
4    我 想 看 挑战 两把 s686 打 突变 团竞 的 游戏 视频     Video-Play
5       我 想 看 和平精英 上 战神 必备 技巧 的 游戏 视频     Video-Play
6  2019 年 古装 爱情 电视剧 小女 花不弃 的 花絮 播放 一下     Video-Play
7        找 一个 2004 年 的 推理剧 给 我 看 一会 呢  FilmTele-Play
8               自驾游 去 深圳 都 经过 那些 地方 啊   Travel-Query
9          给 我 转播 今天 的 女子双打 乒乓球 比赛 现场     Video-Play

In [4]:
datas.describe()

                  0              1
count         12100          12100
unique        12073             12
top     中元节 是 几月 几号  FilmTele-Play
freq              3           1355

In [5]:
X = datas.iloc[:, 0]
y = datas.iloc[:, -1]

encoder = LabelEncoder()
y_encode = encoder.fit_transform(y)

print(encoder.classes_)
class2label = encoder.classes_

['Alarm-Update' 'Audio-Play' 'Calendar-Query' 'FilmTele-Play'
 'HomeAppliance-Control' 'Music-Play' 'Other' 'Radio-Listen'
 'TVProgram-Play' 'Travel-Query' 'Video-Play' 'Weather-Query']

In [6]:
X_train,X_test,y_train,y_test = train_test_split(X,y_encode,test_size=0.2,random_state=42)

In [7]:
vectorizer = TfidfVectorizer()
X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

print(vectorizer.get_feature_names_out())
print(vectorizer.get_feature_names_out().shape)
print(X_train_tfidf.toarray())
print(X_train_tfidf.shape)

['00' '01' '05' ... '龚俊' '龚俊演' '龟兔']
(8776,)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
(9680, 8776)

In [97]:
LR = LogisticRegression()
LR.fit(X_train_tfidf, y_train)
y_pred = LR.predict(X_test_tfidf)
print(y_pred)
print(LR.score(X_test_tfidf,y_test))

[ 9  4 11 ...  4  0  5]
0.8900826446280992

In [111]:
RFC = RandomForestClassifier()
RFC.fit(X_train_tfidf, y_train)
y_pred = RFC.predict(X_test_tfidf)
print(y_pred)
print(RFC.score(X_test_tfidf,y_test))

[ 9  4 11 ...  5  0  5]
0.846694214876033

In [14]:
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
from torch.utils.data import DataLoader,Dataset

class Network_Classifier(nn.Module):
    def __init__(self,in_features,num_classes):
        super(Network_Classifier, self).__init__()
        self.fc_layers = nn.Sequential(
            nn.Linear(in_features,4096),
            nn.ReLU(),
            nn.Linear(4096,1024),
            nn.ReLU(),
            nn.Linear(1024,num_classes),
		)

    def forward(self,x):
        return self.fc_layers(x)

In [15]:
class MyDataset(Dataset):
    def __init__(self, data, target):

        if hasattr(data, "toarray"):
            data = data.toarray()

        data = np.array(data).astype('float32')
        target = np.array(target).astype('int64')

        self.data = torch.from_numpy(data)
        self.target = torch.from_numpy(target)

    def __len__(self):
        return self.data.shape[0]

    def __getitem__(self, idx):
        return self.data[idx], self.target[idx]

In [21]:
batch_size = 64
learning_rate = 0.01
epochs = 200
device = torch.device("mps" if torch.mps.is_available() else "cpu")

In [22]:
train_loader = DataLoader(MyDataset(X_train_tfidf,y_train), batch_size=batch_size, shuffle=True)
test_loader = DataLoader(MyDataset(X_test_tfidf,y_test), batch_size=int(batch_size/2), shuffle=False)

n,m = X_test_tfidf.shape
p = len(np.unique(y_train))

model = Network_Classifier(m,p).to(device)
optimizer = optim.SGD(model.parameters(), lr=learning_rate)
criterion = nn.CrossEntropyLoss()

In [23]:
model.train()
for epoch in range(epochs):
    for batch_idx, (data, target) in enumerate(train_loader):
        data,target = data.to(device), target.to(device)

        optimizer.zero_grad()
        output = model(data)
        loss = criterion(output, target)
        loss.backward()
        optimizer.step()

        if batch_idx % 100 == 0:
            print(f'Train Epoch: {epoch} [{batch_idx * len(data)}/{len(train_loader.dataset)}] Loss: {loss.item():.6f}')

Train Epoch: 0 [0/9680] Loss: 2.485350
Train Epoch: 0 [6400/9680] Loss: 2.466613
Train Epoch: 1 [0/9680] Loss: 2.464716
Train Epoch: 1 [6400/9680] Loss: 2.442105
Train Epoch: 2 [0/9680] Loss: 2.432231
Train Epoch: 2 [6400/9680] Loss: 2.439576
Train Epoch: 3 [0/9680] Loss: 2.415153
Train Epoch: 3 [6400/9680] Loss: 2.385559
Train Epoch: 4 [0/9680] Loss: 2.421940
Train Epoch: 4 [6400/9680] Loss: 2.452553
Train Epoch: 5 [0/9680] Loss: 2.412160
Train Epoch: 5 [6400/9680] Loss: 2.353903
Train Epoch: 6 [0/9680] Loss: 2.362724
Train Epoch: 6 [6400/9680] Loss: 2.379432
Train Epoch: 7 [0/9680] Loss: 2.361529
Train Epoch: 7 [6400/9680] Loss: 2.367631
Train Epoch: 8 [0/9680] Loss: 2.371280
Train Epoch: 8 [6400/9680] Loss: 2.355059
Train Epoch: 9 [0/9680] Loss: 2.331814
Train Epoch: 9 [6400/9680] Loss: 2.359132
Train Epoch: 10 [0/9680] Loss: 2.358633
Train Epoch: 10 [6400/9680] Loss: 2.347937
Train Epoch: 11 [0/9680] Loss: 2.371644
Train Epoch: 11 [6400/9680] Loss: 2.347020
Train Epoch: 12 [0/9680] Loss: 2.291437
Train Epoch: 12 [6400/9680] Loss: 2.367695
Train Epoch: 13 [0/9680] Loss: 2.383860
Train Epoch: 13 [6400/9680] Loss: 2.406030
Train Epoch: 14 [0/9680] Loss: 2.299324
Train Epoch: 14 [6400/9680] Loss: 2.358323
Train Epoch: 15 [0/9680] Loss: 2.384141
Train Epoch: 15 [6400/9680] Loss: 2.344172
Train Epoch: 16 [0/9680] Loss: 2.341557
Train Epoch: 16 [6400/9680] Loss: 2.352636
Train Epoch: 17 [0/9680] Loss: 2.463103
Train Epoch: 17 [6400/9680] Loss: 2.329138
Train Epoch: 18 [0/9680] Loss: 2.309638
Train Epoch: 18 [6400/9680] Loss: 2.339491
Train Epoch: 19 [0/9680] Loss: 2.341840
Train Epoch: 19 [6400/9680] Loss: 2.288547
Train Epoch: 20 [0/9680] Loss: 2.331605
Train Epoch: 20 [6400/9680] Loss: 2.453775
Train Epoch: 21 [0/9680] Loss: 2.314125
Train Epoch: 21 [6400/9680] Loss: 2.358819
Train Epoch: 22 [0/9680] Loss: 2.353417
Train Epoch: 22 [6400/9680] Loss: 2.361917
Train Epoch: 23 [0/9680] Loss: 2.438465
Train Epoch: 23 [6400/9680] Loss: 2.387992
Train Epoch: 24 [0/9680] Loss: 2.358461
Train Epoch: 24 [6400/9680] Loss: 2.479435
Train Epoch: 25 [0/9680] Loss: 2.332859
Train Epoch: 25 [6400/9680] Loss: 2.281731
Train Epoch: 26 [0/9680] Loss: 2.332677
Train Epoch: 26 [6400/9680] Loss: 2.331899
Train Epoch: 27 [0/9680] Loss: 2.384129
Train Epoch: 27 [6400/9680] Loss: 2.259067
Train Epoch: 28 [0/9680] Loss: 2.411813
Train Epoch: 28 [6400/9680] Loss: 2.356464
Train Epoch: 29 [0/9680] Loss: 2.327277
Train Epoch: 29 [6400/9680] Loss: 2.298743
Train Epoch: 30 [0/9680] Loss: 2.384417
Train Epoch: 30 [6400/9680] Loss: 2.327206
Train Epoch: 31 [0/9680] Loss: 2.327592
Train Epoch: 31 [6400/9680] Loss: 2.361496
Train Epoch: 32 [0/9680] Loss: 2.382058
Train Epoch: 32 [6400/9680] Loss: 2.303492
Train Epoch: 33 [0/9680] Loss: 2.383257
Train Epoch: 33 [6400/9680] Loss: 2.358742
Train Epoch: 34 [0/9680] Loss: 2.407991
Train Epoch: 34 [6400/9680] Loss: 2.377812
Train Epoch: 35 [0/9680] Loss: 2.328562
Train Epoch: 35 [6400/9680] Loss: 2.353927
Train Epoch: 36 [0/9680] Loss: 2.328883
Train Epoch: 36 [6400/9680] Loss: 2.301922
Train Epoch: 37 [0/9680] Loss: 2.330173
Train Epoch: 37 [6400/9680] Loss: 2.271964
Train Epoch: 38 [0/9680] Loss: 2.374885
Train Epoch: 38 [6400/9680] Loss: 2.265831
Train Epoch: 39 [0/9680] Loss: 2.263906
Train Epoch: 39 [6400/9680] Loss: 2.297942
Train Epoch: 40 [0/9680] Loss: 2.380539
Train Epoch: 40 [6400/9680] Loss: 2.293398
Train Epoch: 41 [0/9680] Loss: 2.399785
Train Epoch: 41 [6400/9680] Loss: 2.402243
Train Epoch: 42 [0/9680] Loss: 2.302243
Train Epoch: 42 [6400/9680] Loss: 2.300787
Train Epoch: 43 [0/9680] Loss: 2.321290
Train Epoch: 43 [6400/9680] Loss: 2.375588
Train Epoch: 44 [0/9680] Loss: 2.354919
Train Epoch: 44 [6400/9680] Loss: 2.289809
Train Epoch: 45 [0/9680] Loss: 2.432744
Train Epoch: 45 [6400/9680] Loss: 2.317782
Train Epoch: 46 [0/9680] Loss: 2.318730
Train Epoch: 46 [6400/9680] Loss: 2.289254
Train Epoch: 47 [0/9680] Loss: 2.371935
Train Epoch: 47 [6400/9680] Loss: 2.317927
Train Epoch: 48 [0/9680] Loss: 2.339134
Train Epoch: 48 [6400/9680] Loss: 2.318677
Train Epoch: 49 [0/9680] Loss: 2.345686
Train Epoch: 49 [6400/9680] Loss: 2.295071
Train Epoch: 50 [0/9680] Loss: 2.336858
Train Epoch: 50 [6400/9680] Loss: 2.276987
Train Epoch: 51 [0/9680] Loss: 2.308476
Train Epoch: 51 [6400/9680] Loss: 2.414486
Train Epoch: 52 [0/9680] Loss: 2.259808
Train Epoch: 52 [6400/9680] Loss: 2.308526
Train Epoch: 53 [0/9680] Loss: 2.338452
Train Epoch: 53 [6400/9680] Loss: 2.419898
Train Epoch: 54 [0/9680] Loss: 2.364138
Train Epoch: 54 [6400/9680] Loss: 2.363581
Train Epoch: 55 [0/9680] Loss: 2.272117
Train Epoch: 55 [6400/9680] Loss: 2.328892
Train Epoch: 56 [0/9680] Loss: 2.273155
Train Epoch: 56 [6400/9680] Loss: 2.307492
Train Epoch: 57 [0/9680] Loss: 2.395298
Train Epoch: 57 [6400/9680] Loss: 2.280624
Train Epoch: 58 [0/9680] Loss: 2.267071
Train Epoch: 58 [6400/9680] Loss: 2.362281
Train Epoch: 59 [0/9680] Loss: 2.274191
Train Epoch: 59 [6400/9680] Loss: 2.325977
Train Epoch: 60 [0/9680] Loss: 2.329523
Train Epoch: 60 [6400/9680] Loss: 2.241807
Train Epoch: 61 [0/9680] Loss: 2.236520
Train Epoch: 61 [6400/9680] Loss: 2.372074
Train Epoch: 62 [0/9680] Loss: 2.297700
Train Epoch: 62 [6400/9680] Loss: 2.310397
Train Epoch: 63 [0/9680] Loss: 2.316113
Train Epoch: 63 [6400/9680] Loss: 2.289652
Train Epoch: 64 [0/9680] Loss: 2.341125
Train Epoch: 64 [6400/9680] Loss: 2.335010
Train Epoch: 65 [0/9680] Loss: 2.292673
Train Epoch: 65 [6400/9680] Loss: 2.234053
Train Epoch: 66 [0/9680] Loss: 2.218143
Train Epoch: 66 [6400/9680] Loss: 2.241671
Train Epoch: 67 [0/9680] Loss: 2.240341
Train Epoch: 67 [6400/9680] Loss: 2.337371
Train Epoch: 68 [0/9680] Loss: 2.244044
Train Epoch: 68 [6400/9680] Loss: 2.284168
Train Epoch: 69 [0/9680] Loss: 2.266469
Train Epoch: 69 [6400/9680] Loss: 2.258389
Train Epoch: 70 [0/9680] Loss: 2.294664
Train Epoch: 70 [6400/9680] Loss: 2.274742
Train Epoch: 71 [0/9680] Loss: 2.272355
Train Epoch: 71 [6400/9680] Loss: 2.225641
Train Epoch: 72 [0/9680] Loss: 2.303073
Train Epoch: 72 [6400/9680] Loss: 2.329265
Train Epoch: 73 [0/9680] Loss: 2.182004
Train Epoch: 73 [6400/9680] Loss: 2.250931
Train Epoch: 74 [0/9680] Loss: 2.201994
Train Epoch: 74 [6400/9680] Loss: 2.252100
Train Epoch: 75 [0/9680] Loss: 2.187175
Train Epoch: 75 [6400/9680] Loss: 2.095430
Train Epoch: 76 [0/9680] Loss: 2.182753
Train Epoch: 76 [6400/9680] Loss: 2.147964
Train Epoch: 77 [0/9680] Loss: 2.203807
Train Epoch: 77 [6400/9680] Loss: 2.102658
Train Epoch: 78 [0/9680] Loss: 2.198541
Train Epoch: 78 [6400/9680] Loss: 2.187806
Train Epoch: 79 [0/9680] Loss: 2.176583
Train Epoch: 79 [6400/9680] Loss: 2.042846
Train Epoch: 80 [0/9680] Loss: 2.100406
Train Epoch: 80 [6400/9680] Loss: 2.080389
Train Epoch: 81 [0/9680] Loss: 2.271644
Train Epoch: 81 [6400/9680] Loss: 2.052200
Train Epoch: 82 [0/9680] Loss: 2.101394
Train Epoch: 82 [6400/9680] Loss: 1.942643
Train Epoch: 83 [0/9680] Loss: 1.943142
Train Epoch: 83 [6400/9680] Loss: 1.895412
Train Epoch: 84 [0/9680] Loss: 1.978137
Train Epoch: 84 [6400/9680] Loss: 2.029739
Train Epoch: 85 [0/9680] Loss: 2.043753
Train Epoch: 85 [6400/9680] Loss: 1.939732
Train Epoch: 86 [0/9680] Loss: 1.903768
Train Epoch: 86 [6400/9680] Loss: 1.851789
Train Epoch: 87 [0/9680] Loss: 2.012916
Train Epoch: 87 [6400/9680] Loss: 1.917989
Train Epoch: 88 [0/9680] Loss: 1.829455
Train Epoch: 88 [6400/9680] Loss: 1.854428
Train Epoch: 89 [0/9680] Loss: 1.776288
Train Epoch: 89 [6400/9680] Loss: 1.973708
Train Epoch: 90 [0/9680] Loss: 1.883302
Train Epoch: 90 [6400/9680] Loss: 1.892286
Train Epoch: 91 [0/9680] Loss: 2.073988
Train Epoch: 91 [6400/9680] Loss: 1.502331
Train Epoch: 92 [0/9680] Loss: 1.933311
Train Epoch: 92 [6400/9680] Loss: 1.570670
Train Epoch: 93 [0/9680] Loss: 1.729018
Train Epoch: 93 [6400/9680] Loss: 1.670742
Train Epoch: 94 [0/9680] Loss: 1.631974
Train Epoch: 94 [6400/9680] Loss: 1.610901
Train Epoch: 95 [0/9680] Loss: 1.662922
Train Epoch: 95 [6400/9680] Loss: 1.527450
Train Epoch: 96 [0/9680] Loss: 1.412240
Train Epoch: 96 [6400/9680] Loss: 1.460384
Train Epoch: 97 [0/9680] Loss: 1.350219
Train Epoch: 97 [6400/9680] Loss: 1.660044
Train Epoch: 98 [0/9680] Loss: 1.533035
Train Epoch: 98 [6400/9680] Loss: 1.645047
Train Epoch: 99 [0/9680] Loss: 1.396715
Train Epoch: 99 [6400/9680] Loss: 1.492432
Train Epoch: 100 [0/9680] Loss: 1.459800
Train Epoch: 100 [6400/9680] Loss: 1.358233
Train Epoch: 101 [0/9680] Loss: 1.313293
Train Epoch: 101 [6400/9680] Loss: 1.349323
Train Epoch: 102 [0/9680] Loss: 1.263518
Train Epoch: 102 [6400/9680] Loss: 1.465448
Train Epoch: 103 [0/9680] Loss: 1.378396
Train Epoch: 103 [6400/9680] Loss: 1.698848
Train Epoch: 104 [0/9680] Loss: 1.412646
Train Epoch: 104 [6400/9680] Loss: 1.381705
Train Epoch: 105 [0/9680] Loss: 1.455546
Train Epoch: 105 [6400/9680] Loss: 1.261582
Train Epoch: 106 [0/9680] Loss: 1.219190
Train Epoch: 106 [6400/9680] Loss: 1.074797
Train Epoch: 107 [0/9680] Loss: 1.178321
Train Epoch: 107 [6400/9680] Loss: 1.212510
Train Epoch: 108 [0/9680] Loss: 1.259539
Train Epoch: 108 [6400/9680] Loss: 1.148426
Train Epoch: 109 [0/9680] Loss: 1.071126
Train Epoch: 109 [6400/9680] Loss: 1.075152
Train Epoch: 110 [0/9680] Loss: 1.170957
Train Epoch: 110 [6400/9680] Loss: 1.260163
Train Epoch: 111 [0/9680] Loss: 1.146521
Train Epoch: 111 [6400/9680] Loss: 0.942676
Train Epoch: 112 [0/9680] Loss: 1.114961
Train Epoch: 112 [6400/9680] Loss: 1.078757
Train Epoch: 113 [0/9680] Loss: 1.205958
Train Epoch: 113 [6400/9680] Loss: 0.913970
Train Epoch: 114 [0/9680] Loss: 1.123581
Train Epoch: 114 [6400/9680] Loss: 0.897332
Train Epoch: 115 [0/9680] Loss: 0.745084
Train Epoch: 115 [6400/9680] Loss: 1.110763
Train Epoch: 116 [0/9680] Loss: 0.930916
Train Epoch: 116 [6400/9680] Loss: 0.866333
Train Epoch: 117 [0/9680] Loss: 0.844656
Train Epoch: 117 [6400/9680] Loss: 1.029064
Train Epoch: 118 [0/9680] Loss: 0.981050
Train Epoch: 118 [6400/9680] Loss: 0.926769
Train Epoch: 119 [0/9680] Loss: 0.952381
Train Epoch: 119 [6400/9680] Loss: 0.683946
Train Epoch: 120 [0/9680] Loss: 1.069282
Train Epoch: 120 [6400/9680] Loss: 1.033966
Train Epoch: 121 [0/9680] Loss: 1.013041
Train Epoch: 121 [6400/9680] Loss: 0.668098
Train Epoch: 122 [0/9680] Loss: 0.941396
Train Epoch: 122 [6400/9680] Loss: 0.932907
Train Epoch: 123 [0/9680] Loss: 0.888325
Train Epoch: 123 [6400/9680] Loss: 0.626533
Train Epoch: 124 [0/9680] Loss: 0.799054
Train Epoch: 124 [6400/9680] Loss: 0.704804
Train Epoch: 125 [0/9680] Loss: 0.884823
Train Epoch: 125 [6400/9680] Loss: 0.703034
Train Epoch: 126 [0/9680] Loss: 0.813885
Train Epoch: 126 [6400/9680] Loss: 0.686979
Train Epoch: 127 [0/9680] Loss: 0.620342
Train Epoch: 127 [6400/9680] Loss: 0.801300
Train Epoch: 128 [0/9680] Loss: 0.697471
Train Epoch: 128 [6400/9680] Loss: 0.703123
Train Epoch: 129 [0/9680] Loss: 0.690041
Train Epoch: 129 [6400/9680] Loss: 0.668860
Train Epoch: 130 [0/9680] Loss: 0.751748
Train Epoch: 130 [6400/9680] Loss: 0.512469
Train Epoch: 131 [0/9680] Loss: 0.673871
Train Epoch: 131 [6400/9680] Loss: 0.598565
Train Epoch: 132 [0/9680] Loss: 0.617972
Train Epoch: 132 [6400/9680] Loss: 0.638900
Train Epoch: 133 [0/9680] Loss: 0.626356
Train Epoch: 133 [6400/9680] Loss: 0.666011
Train Epoch: 134 [0/9680] Loss: 0.465342
Train Epoch: 134 [6400/9680] Loss: 0.664431
Train Epoch: 135 [0/9680] Loss: 0.546417
Train Epoch: 135 [6400/9680] Loss: 0.620476
Train Epoch: 136 [0/9680] Loss: 0.445479
Train Epoch: 136 [6400/9680] Loss: 0.656002
Train Epoch: 137 [0/9680] Loss: 0.696457
Train Epoch: 137 [6400/9680] Loss: 0.641307
Train Epoch: 138 [0/9680] Loss: 0.485470
Train Epoch: 138 [6400/9680] Loss: 0.628228
Train Epoch: 139 [0/9680] Loss: 0.783249
Train Epoch: 139 [6400/9680] Loss: 0.683138
Train Epoch: 140 [0/9680] Loss: 0.574262
Train Epoch: 140 [6400/9680] Loss: 0.466108
Train Epoch: 141 [0/9680] Loss: 0.490230
Train Epoch: 141 [6400/9680] Loss: 0.647006
Train Epoch: 142 [0/9680] Loss: 0.555204
Train Epoch: 142 [6400/9680] Loss: 0.462977
Train Epoch: 143 [0/9680] Loss: 0.683466
Train Epoch: 143 [6400/9680] Loss: 0.604436
Train Epoch: 144 [0/9680] Loss: 0.675223
Train Epoch: 144 [6400/9680] Loss: 0.487502
Train Epoch: 145 [0/9680] Loss: 0.615270
Train Epoch: 145 [6400/9680] Loss: 0.573216
Train Epoch: 146 [0/9680] Loss: 0.494055
Train Epoch: 146 [6400/9680] Loss: 0.649829
Train Epoch: 147 [0/9680] Loss: 0.503122
Train Epoch: 147 [6400/9680] Loss: 0.486041
Train Epoch: 148 [0/9680] Loss: 0.375617
Train Epoch: 148 [6400/9680] Loss: 0.489705
Train Epoch: 149 [0/9680] Loss: 0.843269
Train Epoch: 149 [6400/9680] Loss: 0.557457
Train Epoch: 150 [0/9680] Loss: 0.532454
Train Epoch: 150 [6400/9680] Loss: 0.623898
Train Epoch: 151 [0/9680] Loss: 0.507878
Train Epoch: 151 [6400/9680] Loss: 0.323081
Train Epoch: 152 [0/9680] Loss: 0.436992
Train Epoch: 152 [6400/9680] Loss: 0.617717
Train Epoch: 153 [0/9680] Loss: 0.391855
Train Epoch: 153 [6400/9680] Loss: 0.499279
Train Epoch: 154 [0/9680] Loss: 0.428454
Train Epoch: 154 [6400/9680] Loss: 0.496346
Train Epoch: 155 [0/9680] Loss: 0.408279
Train Epoch: 155 [6400/9680] Loss: 0.405828
Train Epoch: 156 [0/9680] Loss: 0.428566
Train Epoch: 156 [6400/9680] Loss: 0.488550
Train Epoch: 157 [0/9680] Loss: 0.504348
Train Epoch: 157 [6400/9680] Loss: 0.424191
Train Epoch: 158 [0/9680] Loss: 0.403131
Train Epoch: 158 [6400/9680] Loss: 0.193803
Train Epoch: 159 [0/9680] Loss: 0.381242
Train Epoch: 159 [6400/9680] Loss: 0.607942
Train Epoch: 160 [0/9680] Loss: 0.509199
Train Epoch: 160 [6400/9680] Loss: 0.386122
Train Epoch: 161 [0/9680] Loss: 0.429221
Train Epoch: 161 [6400/9680] Loss: 0.457812
Train Epoch: 162 [0/9680] Loss: 0.434407
Train Epoch: 162 [6400/9680] Loss: 0.371731
Train Epoch: 163 [0/9680] Loss: 0.309791
Train Epoch: 163 [6400/9680] Loss: 0.382118
Train Epoch: 164 [0/9680] Loss: 0.317644
Train Epoch: 164 [6400/9680] Loss: 0.317614
Train Epoch: 165 [0/9680] Loss: 0.311082
Train Epoch: 165 [6400/9680] Loss: 0.338343
Train Epoch: 166 [0/9680] Loss: 0.406173
Train Epoch: 166 [6400/9680] Loss: 0.312401
Train Epoch: 167 [0/9680] Loss: 0.330935
Train Epoch: 167 [6400/9680] Loss: 0.371278
Train Epoch: 168 [0/9680] Loss: 0.355594
Train Epoch: 168 [6400/9680] Loss: 0.340138
Train Epoch: 169 [0/9680] Loss: 0.408865
Train Epoch: 169 [6400/9680] Loss: 0.308524
Train Epoch: 170 [0/9680] Loss: 0.424231
Train Epoch: 170 [6400/9680] Loss: 0.353091
Train Epoch: 171 [0/9680] Loss: 0.286923
Train Epoch: 171 [6400/9680] Loss: 0.382759
Train Epoch: 172 [0/9680] Loss: 0.391517
Train Epoch: 172 [6400/9680] Loss: 0.367396
Train Epoch: 173 [0/9680] Loss: 0.342783
Train Epoch: 173 [6400/9680] Loss: 0.360442
Train Epoch: 174 [0/9680] Loss: 0.313320
Train Epoch: 174 [6400/9680] Loss: 0.372100
Train Epoch: 175 [0/9680] Loss: 0.332442
Train Epoch: 175 [6400/9680] Loss: 0.374841
Train Epoch: 176 [0/9680] Loss: 0.316213
Train Epoch: 176 [6400/9680] Loss: 0.213455
Train Epoch: 177 [0/9680] Loss: 0.285287
Train Epoch: 177 [6400/9680] Loss: 0.232926
Train Epoch: 178 [0/9680] Loss: 0.317858
Train Epoch: 178 [6400/9680] Loss: 0.333656
Train Epoch: 179 [0/9680] Loss: 0.240272
Train Epoch: 179 [6400/9680] Loss: 0.310955
Train Epoch: 180 [0/9680] Loss: 0.267064
Train Epoch: 180 [6400/9680] Loss: 0.238192
Train Epoch: 181 [0/9680] Loss: 0.236401
Train Epoch: 181 [6400/9680] Loss: 0.346236
Train Epoch: 182 [0/9680] Loss: 0.292959
Train Epoch: 182 [6400/9680] Loss: 0.275091
Train Epoch: 183 [0/9680] Loss: 0.288839
Train Epoch: 183 [6400/9680] Loss: 0.313114
Train Epoch: 184 [0/9680] Loss: 0.271025
Train Epoch: 184 [6400/9680] Loss: 0.266214
Train Epoch: 185 [0/9680] Loss: 0.335327
Train Epoch: 185 [6400/9680] Loss: 0.194203
Train Epoch: 186 [0/9680] Loss: 0.395774
Train Epoch: 186 [6400/9680] Loss: 0.310924
Train Epoch: 187 [0/9680] Loss: 0.133869
Train Epoch: 187 [6400/9680] Loss: 0.181275
Train Epoch: 188 [0/9680] Loss: 0.200444
Train Epoch: 188 [6400/9680] Loss: 0.215608
Train Epoch: 189 [0/9680] Loss: 0.195122
Train Epoch: 189 [6400/9680] Loss: 0.440865
Train Epoch: 190 [0/9680] Loss: 0.275775
Train Epoch: 190 [6400/9680] Loss: 0.198706
Train Epoch: 191 [0/9680] Loss: 0.247217
Train Epoch: 191 [6400/9680] Loss: 0.339851
Train Epoch: 192 [0/9680] Loss: 0.186588
Train Epoch: 192 [6400/9680] Loss: 0.209371
Train Epoch: 193 [0/9680] Loss: 0.264355
Train Epoch: 193 [6400/9680] Loss: 0.153347
Train Epoch: 194 [0/9680] Loss: 0.191400
Train Epoch: 194 [6400/9680] Loss: 0.273198
Train Epoch: 195 [0/9680] Loss: 0.255188
Train Epoch: 195 [6400/9680] Loss: 0.312427
Train Epoch: 196 [0/9680] Loss: 0.229320
Train Epoch: 196 [6400/9680] Loss: 0.257289
Train Epoch: 197 [0/9680] Loss: 0.254807
Train Epoch: 197 [6400/9680] Loss: 0.232924
Train Epoch: 198 [0/9680] Loss: 0.397062
Train Epoch: 198 [6400/9680] Loss: 0.226408
Train Epoch: 199 [0/9680] Loss: 0.206349
Train Epoch: 199 [6400/9680] Loss: 0.196463

In [24]:
model.eval()
test_loss = 0
correct = 0
with torch.no_grad():
    for data, target in test_loader:
        data, target = data.to(device), target.to(device)
        output = model(data)
        test_loss += criterion(output, target).item()
        pred = output.argmax(dim=1, keepdim=True)
        # output.sort(dim=1, descending=True)

        correct += pred.eq(target.view_as(pred)).sum().item()

    test_loss /= len(test_loader.dataset)
    accuracy = 100. * correct / len(test_loader.dataset)
    print(f'\nTest set: Average loss: {test_loss:.4f}, Accuracy: {correct}/{len(test_loader.dataset)} ({accuracy:.2f}%)\n')

Test set: Average loss: 0.0151, Accuracy: 2093/2420 (86.49%)

Connected to: <socket.socket fd=84, family=2, type=1, proto=0, laddr=('127.0.0.1', 55231), raddr=('127.0.0.1', 55126)>.

In [119]:

def predict(text,k,model):
    import jieba
    text_cut = [" ".join(jieba.lcut(i)) for i in text]
    # print("分割结果：",text_cut)
    text_cut_vector = vectorizer.transform(text_cut)
    text_pre = model.predict(text_cut_vector)
    texr_pre_proba = model.predict_proba(text_cut_vector)
    text_pre_k = np.argsort(-texr_pre_proba,axis=1)[:,:k]
    texr_pre_pro = F.softmax(texr_pre_proba)[:,k]
    print(texr_pre_pro)
    print(f"{model}概率最大的{k}个类型：",class2label[text_pre_k])
    print(f"{model}概率最大的类型：",class2label[text_pre])

In [124]:
text = ["我听王力宏",
        "我听陶喆",
        "我看饺子的哪吒2",
        "我看周星驰的功夫"]
k = 3

predict(text,k,LR)
predict(text,k,RFC)

LogisticRegression()概率最大的3个类型： [['Music-Play' 'Video-Play' 'FilmTele-Play']
 ['FilmTele-Play' 'Music-Play' 'Radio-Listen']
 ['FilmTele-Play' 'Video-Play' 'Music-Play']
 ['FilmTele-Play' 'Music-Play' 'Video-Play']]
LogisticRegression()概率最大的类型： ['Music-Play' 'FilmTele-Play' 'FilmTele-Play' 'FilmTele-Play']
RandomForestClassifier()概率最大的3个类型： [['Music-Play' 'FilmTele-Play' 'Radio-Listen']
 ['Music-Play' 'FilmTele-Play' 'Radio-Listen']
 ['Music-Play' 'FilmTele-Play' 'Radio-Listen']
 ['FilmTele-Play' 'Music-Play' 'HomeAppliance-Control']]
RandomForestClassifier()概率最大的类型： ['Music-Play' 'Music-Play' 'Music-Play' 'FilmTele-Play']